### ISSUE TITLE
Issue: Irrelevant Readme.md

### ISSUE THREAD

**Issue by jiveshkalra** [Eklavya-sus/Spotify_Api#1]
Readme.md file should tell people more about the project and how they can recreate it and contribute, which is incomplete in this repository as it is only a template readme.md file of reactjs

**Comment by Eklavya-sus** [comment]
Yup, that's right. I will update it as soon as possible.

**Comment by jiveshkalra** [comment]
can you assign this task to me? I can do it if you want

**Comment by Eklavya-sus** [comment]
Sure

**Comment by jiveshkalra** [comment]
I have made the updates , kindly check the Pull Request

**Comment by alvin-dennis** [comment]
@Eklavya-sus I can make a much more detailed readme with contributing procedures focused and other stuff. Pls assign me this issue
