### ISSUE TITLE
BUG : Login not working on vercel app

### ISSUE THREAD

**Issue by jiveshkalra** [Eklavya-sus/Spotify_Api#2]
Due to the 'static' links of localhost the login process doesnt work on server (vercel)
when I try to login I get redirected to a localhost page -> 
![image](https://github.com/Eklavya-sus/Spotify_Api/assets/127482713/b68c658a-2806-4c0a-93fa-e530e0fa96ae) 

What I propose to do ->
- [ ] Replacing Statically typed URLs with the dynamic ones

**Comment by Eklavya-sus** [comment]
sure go for it
